name = "deviantclaw-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "deviantclaw.art", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "deviantclaw"
database_id = "c2c2c64f-ca80-4059-b2a7-560927b9d384"

[[r2_buckets]]
binding = "THUMBNAILS"
bucket_name = "deviantclaw-thumbnails"
